name: Web App Build
on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]
jobs:
  auto-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: "Install deps"
        working-directory: ./web_app
        run: yarn install
      - name: "Build App"
        working-directory: ./web_app
        run: npm run build